# Generated by Django 5.0.2 on 2024-02-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
