# Generated by Django 5.0.2 on 2024-02-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_alter_like_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
