# Generated by Django 5.0.2 on 2024-02-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_userprofile_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
